### ISSUE TITLE
Error while run gatsby build

### ISSUE THREAD

**Issue by lmortellaro** [italia/design-italia-gatsby-starterkit#11]
Everything works fine when i run the develop script but when I run build this error occurs:

ERROR #95313

 

Building static HTML failed

 

See our docs page for more info on this error: https://gatsby.dev/debug-html

 

  543 |   className: PropTypes.string,
  544 |   scrollToRef: PropTypes.shape({
> 545 |     current: PropTypes.instanceOf(Element)
      |                       ^
  546 |   })
  547 | };
  548 |

 

  WebpackError: ReferenceError: Element is not defined

 

  - design-react-kit.es.js:545
    node_modules/design-react-kit/dist/design-react-kit.es.js:545:23

 

  - header.js:1
    src/components/header.js:1:1

 

  - 404.js:1
    src/pages/404.js:1:1

 

  - sync-requires.js:8
    node_modules/$virtual/sync-requires.js:8:53

Changing line 545 from current: PropTypes.instanceOf(Element) to current: PropTypes.any I get no more errors but I'm not sure at all this is a proper solution.
Can you help me please?

**Comment by dej611** [comment]
It's a `design-reeact-kit` issue: the fix is on the way => https://github.com/italia/design-react-kit/pull/604

**Comment by dej611** [comment]
The fix is now released: 8a52c46139153ec2c7fe9899bf55b14048a7a7ae
In case of existing projects, just bump `design-react-kit` and `bootstrap-italia` dependencies as in the commit.
