### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by dej611** [italia/design-italia-gatsby-starterkit#6]
**Is your feature request related to a problem? Please describe.**
Not really, just a proposal.

**Describe the solution you'd like**
Rename the repo into `design-gatsby-starter-kit` as proposed by @libremente.

Things to do for the change:
* [x] Update `README.md` and `README.en.md`
* [x] Update gatsby starter kit json entry
* [x] Update GSoC document

**Describe alternatives you've considered**
Keep it as is.

**Comment by libremente** [comment]
Links fixed in GSoC page: https://github.com/italia/developers.italia.it/commit/adb1f0454bc1b4023fc393a2a153ad4b9c982397
